---
title: SPARKLE Training Course
subtitle: Fitting Models - Part 2
format:
    training-html: default
presenter: "Dr Eamon Conway"
contributors: [Dr Eamon Conway]
---

## Introduction

The examples provided in [Fitting Models - Part 1](../session_fitting_models/fitting_models.qmd) have focused on probability distributions and determining their parameters.
But what if the model you have written down is not actually a probability distribution?
What if you wrote down a system of ordinary differential equations (or partial differential equations)?
We will look at the development of different model systems and how to use the tools we learnt in the last workshop to fit parameters.

## Deterministic models
### Maximum likelihood for deterministic models

Consider a deterministic model $f: (\mathcal{M},\theta) \rightarrow \mathcal{O}$, which maps an input space $\mathcal{M}$ into an output space $\mathcal{O}$, dependent upon the parameters $\theta$.
We then make the assumption that the data observed, $D$, is generated from a distribution $Q(\cdot|\mathcal{O},\theta)$ that depends on the output space and the parameters of interest.

::: {.callout-note title="Normal data example" collapse="true"}
For a simple example, lets assume that the data is independent and that,
$$
D_i \sim \mathcal{N}(\mu_i(\theta) = f(\mathcal{M}_i,\theta),\sigma^2),
$$
where $D_i$ is the $i$th data point, $\mu_i$ is the mean value of the $i$th data point (given by a deterministic model $f$), and $\sigma^2$ is the variance of the sample.

The likelihood for this example would be,
$$
\mathcal{L}(\theta) = \prod_{i=1}^N \frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{(D_i - \mu_i(\theta))^2}{2\sigma^2}}.
$$
Therefore we have that the log-likelihood is,
$$
\log \mathcal{L}(\theta) = K - \sum_{i=1}^N (D_i - \mu(\theta))^2,
$$
where $K$ is all constant terms.
The maximum likelihood solution is,
$$
\hat{\theta} = \max  - \sum_{i=1}^N (D_i - \mu(\theta))^2,
$$
which is the same solution to nonlinear least squares!
Therefore, if we choose that $Q(\cdot|\mathcal{O},\theta) = \mathcal{N}(\cdot|\mu=f(\mathcal{M},\theta),\sigma^2)$, with appropriate constraints on the form of $f$, then we are solving a nonlinear least squares problem (demonstrated in next example).

If you are familiar with using nonlinear least squares to fit your models, then you are now also familiar with using maximum likelihood method to fit your models.
:::

### Bayesian inference for deterministic models
Taking the same deterministic model as before, $f: (\mathcal{M},\theta) \rightarrow \mathcal{O}$, we can use Bayesian Inference.

We then make the assumption that the data observed, $D$, is generated from a distribution $Q(\cdot|\mathcal{O},\theta)$ that depends on the output space and the parameters of interest.

### Infectious disease data

What model could we fit to the data.

How long is someone infectious for? 

How long is someone symptomatic

What data limitations are there? 

The data that you collect should be tied to the model and allow you to
understand the parameters.
If we wanted to understand $R_0$, what data should we collect?
What model would we use?

What other models could be fit? Markov models

Markov processes can also be used to model data. 
Conditional independence means that we can get a likelihood through
multiplication


### Fitting an SIR model

It is common to work with simulated data when learning how to fit models. 
First we use the model to obtain a random sample of data points. 
Next we fit the model to the simulated data to see if we obtain the parameters that we put into our model. 
This process allows us to compare our fitting algorithms to known truths and gives confidence that we will be correct when working with real data.

```{r echo=FALSE, filename="generate_sir_data.r"}
sir_model <- function(t, state, parameters) {
  with(as.list(c(state, parameters)), {
    N <- S + I + R
    beta <- R0 * gamma

    new_infections <- beta * S * I / N
    recoveries <- gamma * I

    list(c(
      dS = -new_infections,
      dI = new_infections - recoveries,
      dR = recoveries
    ))
  })
}

sir_parameters <- c(R0 = 2.2, gamma = 1 / 5)
sir_state <- c(S = 980, I = 20, R = 0)
sir_times <- seq(0, 20, by = 1)

sir_solution <- as.data.frame(deSolve::ode(
  y = sir_state,
  times = sir_times,
  func = sir_model,
  parms = sir_parameters
))

calculate_incidence <- function(S,I,R,parameters){
  with(as.list(c(parameters)), {
    N <- S + I + R
    beta <- R0 * gamma
    new_infections <- beta * S * I / N
    return(rpois(n = length(new_infections), lambda = new_infections))
  })
}

sir_incidence <- sir_solution |> 
    dplyr::mutate(incidence = calculate_incidence(S,I,R,sir_parameters)) |> 
    dplyr::select(time,incidence)

knitr::kable(sir_incidence)
```

### Multi-patch SIR model
1) What data should we collect for a patch based SIR model?
2) 
What data would be needed to fit a multi-patch sir model

## Age stratified SIR model

1) What data should we collect for an age stratified SIR model?

## Stochastic models

### Markov Models

### Renewal models
Consider an infectious disease model based on the renewal equation.
$$
I_t = R_t\sum_i g_i I_{t-i-1}
$$

We will assume that the daily incidence is Poisson distributed with a mean given by $I_t$. 

1) What would the likelihood be?

:::{.callout-note}
$$
p(\mathbf{D}|\mathbf{I}) = \prod_t \frac{{I}_t^{D_t} \exp(-I_t)}{D_t!}
$$
We are taking each data point and assuming conditional independence.
:::

2) What are the unknown parameters? 

3) Could we set a prior? 


4) Assume that $g_i = $.

What is the maximum likelihood estimate for $R_5$?

## Pitfalls of model fitting

When fitting mathematical models to data you must be able to evaluate the model relatively efficiently.
Some models can be solved with minimal computational effort and then no real thought has to go into the best option for fitting.
If you have a model that takes hours to run for a single parameter combination then you now have to think about your best approach.

## Agent based models

Agent based models are wide spread in infectious disease modelling. 
Instead of applying heterogeneities to whole groups of people (for example vaccinated), we can apply the heterogeneity at the per individual level. 
That is we have an infected individual rather than $N$ individuals in the infected compartment. 
Making the switch from counting the number of individuals in a homogenous state to individual specific behaviour gives the modeller extreme control over the system.

:::{.activity}
Let us consider the transmission of COVID-19 to learn about the concepts in agent based modelling.
What individual level heterogeneities do you think is important to account for in the transmission of COVID-19?
:::

```{=html}
<textarea cols="127" rows="5"></textarea>
```

:::{.activity}
What individual level heterogeneities do you think is important to account for in vector borne disease transmission?
:::

```{=html}
<textarea cols="127" rows="5"></textarea>
```

### Exercises
1) Agent based models seem extremely powerful - what are the downsides?
2) What are the benefits of agent based models?
3) What situation would call for an agent based model over a deterministic model?
4) Do agent based models work with any of the fitting methods that we discussed in the last two sessions?


Fitting an agent based model is complicated, often too complicated. 
Each parameter is often fit using a much simpler stochastic model fitting real world data.


## Real applications of model fitting
In my opinion, the hardest part of infectious disease modelling is incorporating your data into your model and obtaining a reasonable fit. 
This process involves knowledge of data, mathematical modelling, statistics, and computing to make sure that the correct answer is obtained.
This is an interdisciplinary pursuit and its important to make sure that your results are reliable. 
This introduces the super important topic of reproducibility. 

