project:
  title: "Modelling Infectious Diseases"
  type: website
toc: true
format:
  html:
    theme: cosmo
    css: style_training.css
    title-block-style: none
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true

  

execute:
  freeze: auto

website:
  navbar:
    style: floating
    search: true
    logo: logo.png
    border: true
    background: "#4BA5AB"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Sessions"
        menu:
          - text: "Session 1: Introduction to version control"
          - href: session_spatial_models/session_spatial_models.qmd
    
  page-footer:
    left: |
      For more information or to report issues, please contact <a href='mailto:spectrum-spark@unimelb.edu.au'>the consortia project inbox</a>. <br>
      © July 2025 SPARKLE
    right: |
      SPARKLE is funded by the Australian Department of Foreign Affairs and Trade (DFAT)
    background: "#4BA5AB"
    foreground: "#FFFFFF"
      
