---
title: What if my model is not stochastic?
---

The examples provided in within this [model fitting](model-fitting.qmd) section have focused on probability distributions and determining their parameters.
But what if the model you have written down is not actually a probability distribution?
What if you wrote down a system of ordinary differential equations (or partial differential equations)?
Are there any approaches that can be used to fit these models?
Unsurprisingly yes, and the majority of which are based on maximum likelihood or Bayesian inference.

### Maximum likelihood for deterministic models

Consider a deterministic model $f: (\mathcal{M},\theta) \rightarrow \mathcal{O}$, which maps an input space $\mathcal{M}$ into an output space $\mathcal{O}$, dependent upon the parameters $\theta$.
We then make the assumption that the data observed, $D$, is generated from a distribution $Q(\cdot|\mathcal{O},\theta)$ that depends on the output space and the parameters of interest.

::: {.callout-note title="Nonlinear Least Squares"}
If we choose that $Q(\cdot|\mathcal{O},\theta) = \mathcal{N}(\cdot|\mu=f(\mathcal{M},\theta),\sigma^2)$, with appropriate constraints on the form of $f$, then we are solving a nonlinear least squares problem (demonstrated in next example).
:::

::: {.callout-note title="Normal data example" collapse="true"}
For a simple example, lets assume that the data is independent and that,
$$
D_i \sim \mathcal{N}(\mu_i(\theta) = f(\mathcal{M}_i,\theta),\sigma^2),
$$
where $D_i$ is the $i$th data point, $\mu_i$ is the mean value of the $i$th data point (given by a deterministic model $f$), and $\sigma^2$ is the variance of the sample.

The likelihood for this example would be,
$$
\mathcal{L}(\theta) = \prod_{i=1}^N \frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{(D_i - \mu_i(\theta))^2}{2\sigma^2}}.
$$
Therefore we have that the log-likelihood is,
$$
\log \mathcal{L}(\theta) = K - \sum_{i=1}^N (D_i - \mu(\theta))^2,
$$
where $K$ is all constant terms.
The maximum likelihood solution is,
$$
\hat{\theta} = \arg \max  - \sum_{i=1}^N (D_i - \mu(\theta))^2,
$$
which is the same solution to nonlinear least squares!
If you are familiar with using nonlinear least squares to fit your models, then you are now also familiar with using maximum likelihood method to fit your models.
:::

### Bayesian inference for deterministic models
Taking the same deterministic model as before, $f: (\mathcal{M},\theta) \rightarrow \mathcal{O}$, we can use Bayesian Inference.

We then make the assumption that the data observed, $D$, is generated from a distribution $Q(\cdot|\mathcal{O},\theta)$ that depends on the output space and the parameters of interest.

::: {.callout-note title="SIR model"}

:::

## Pitfalls of model fitting

When fitting mathematical models to data you must be able to evaluate the model relatively efficiently.
There is no escaping the fact that the model must be run repeatedly to obtain information on the fit.
Some models can be solved with minimal computational effort and then no real thought has to go into the best option for fitting.
If you have a model that takes hours to run for a single parameter combination then you now have to think about your best approach.


